"""
Generate one markdown model card per trained model in the registry.

Usage::

    python -m ml.scripts.generate_model_cards
    python -m ml.scripts.generate_model_cards --out .github/model_cards
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Optional

from ml.features import FEATURE_COLUMNS
from ml.model_registry import load_registry, default_registry_path
from ml.paths import repository_root


_AUTO_GEN_NOTE = (
    "> **Note:** This model card was auto-generated by `ml.scripts.generate_model_cards`. "
    "Re-run `python -m ml.scripts.generate_model_cards` to refresh after retraining."
)


def _fmt_float(val: Optional[float], decimals: int = 4) -> str:
    if val is None or (isinstance(val, float) and math.isnan(val)):
        return "n/a"
    return f"{val:.{decimals}f}"


def _load_manifest_metrics(manifest_path: Optional[str], repo_root: Path) -> Dict[str, Any]:
    """Load additional metrics from manifest.json if available."""
    if not manifest_path:
        return {}
    abs_path = repo_root / manifest_path
    if not abs_path.is_file():
        return {}
    try:
        with abs_path.open(encoding="utf-8") as f:
            data = json.load(f)
        return data
    except Exception:
        return {}


def _render_card(entry: Dict[str, Any], manifest: Dict[str, Any]) -> str:
    region_id: str = entry.get("region_id", "unknown")
    segment: str = entry.get("segment", "unknown")
    r2_val: Optional[float] = entry.get("r2_val")
    half_width: Optional[float] = entry.get("conformal_half_width")
    trained_at: str = entry.get("trained_at_utc", "")
    trained_short = trained_at[:19] if trained_at else "—"

    # Pull deeper metrics from manifest when available
    man_metrics: Dict[str, Any] = manifest.get("metrics", {})
    r2_xgb = man_metrics.get("r2_val_xgboost")
    r2_lgb = man_metrics.get("r2_val_lightgbm")
    r2_ens = man_metrics.get("r2_val_ensemble_mean", r2_val)

    man_uncertainty: Dict[str, Any] = manifest.get("uncertainty", {})
    cal_n = man_uncertainty.get("calibration_n")
    coverage = man_uncertainty.get("coverage", 0.9)
    model_version = manifest.get("model_version", "—")

    feature_list = "\n".join(f"- `{col}`" for col in FEATURE_COLUMNS)

    # Build RMSE note — not stored in registry, but may be in manifest (currently absent)
    rmse_note = ""
    # If future manifests add rmse we can surface it here; for now omit

    r2_table_rows = ""
    if r2_xgb is not None:
        r2_table_rows += f"| XGBoost (val) | {_fmt_float(r2_xgb)} |\n"
    if r2_lgb is not None:
        r2_table_rows += f"| LightGBM (val) | {_fmt_float(r2_lgb)} |\n"
    if r2_ens is not None:
        r2_table_rows += f"| Ensemble mean (val) | **{_fmt_float(r2_ens)}** |\n"
    if not r2_table_rows:
        r2_table_rows = "| Ensemble mean (val) | n/a |\n"

    cal_n_str = str(cal_n) if cal_n is not None else "—"
    coverage_pct = int(coverage * 100)

    card = f"""\
# Mframapa PM2.5 Model Card — `{region_id}` / `{segment}`

{_AUTO_GEN_NOTE}

---

## Model identity

| Field | Value |
|---|---|
| **Model name** | Mframapa PM2.5 — {region_id} / {segment} |
| **Version** | {model_version} |
| **Region** | {region_id} |
| **Segment** | {segment} |
| **Training date (UTC)** | {trained_short} |

## Intended use

Daily PM2.5 surface concentration point estimates (µg/m³) for African locations
within the **{region_id}** sub-region classified as **{segment}**.

Not a regulatory measurement. Results should not be used as a substitute for
ground-truth sensor data.

## Performance metrics

| Metric | Value |
|---|---|
{r2_table_rows}| Conformal half-width (±µg/m³) | {_fmt_float(half_width, 3)} |

{rmse_note}

## Uncertainty quantification

- **Method:** Split conformal prediction using absolute residuals
- **Coverage target:** {coverage_pct}%
- **Calibration set size:** {cal_n_str} samples
- A prediction interval is computed as `[ŷ − half_width, ŷ + half_width]` and
  achieves approximately {coverage_pct}% marginal coverage on the calibration split.

## Input features

The model consumes the following {len(FEATURE_COLUMNS)} features in order:

{feature_list}

## Architecture

An ensemble of two gradient-boosted tree models:

1. **XGBoost** (`xgboost.json`) — 200 estimators, max depth 6, lr 0.06
2. **LightGBM** (`lightgbm.txt`) — up to 300 rounds with early stopping, 48 leaves, lr 0.06

Final prediction is the unweighted mean of both model outputs (`ensemble_mean`).

## Ethical and safety notes

- This model is trained on satellite-derived and reanalysis features; ground sensor
  coverage in Africa is sparse, which may affect regional accuracy.
- Cloud cover and satellite data gaps can introduce systematic errors.
- Do not use outputs for health advisories, regulatory compliance, or emergency response
  without validation against local sensor data.

## How to regenerate this card

```bash
python -m ml.scripts.generate_model_cards
```

## Retraining

See `.github/workflows/retrain_models.yml` for the automated retraining workflow.
"""
    return card


def generate_cards(
    registry_path: Optional[Path] = None,
    out_dir: Optional[Path] = None,
) -> int:
    repo_root = repository_root()
    reg_path = registry_path or default_registry_path(repo_root / "ml")
    registry = load_registry(reg_path)
    models: List[Dict[str, Any]] = registry.get("models", [])

    trained = [m for m in models if m.get("r2_val") is not None or m.get("xgboost_path")]

    if not trained:
        print(
            "No trained models found in registry. Train models first, then re-run this script."
        )
        return 0

    dest = out_dir or (repo_root / ".github" / "model_cards")
    dest.mkdir(parents=True, exist_ok=True)

    written = 0
    for entry in trained:
        region_id = entry.get("region_id", "unknown")
        segment = entry.get("segment", "unknown")
        manifest = _load_manifest_metrics(entry.get("manifest_path"), repo_root)
        card_text = _render_card(entry, manifest)
        card_path = dest / f"{region_id}_{segment}.md"
        with card_path.open("w", encoding="utf-8") as f:
            f.write(card_text)
        print(f"  Wrote {card_path.relative_to(repo_root)}")
        written += 1

    print(f"\n{written} model card(s) written to {dest.relative_to(repo_root)}")
    return written


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate markdown model cards for all trained regional PM2.5 models."
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=None,
        metavar="DIR",
        help="Output directory for model cards (defaults to .github/model_cards).",
    )
    ap.add_argument(
        "--registry",
        type=Path,
        default=None,
        metavar="JSON",
        help="Path to model_registry.json (defaults to ml/data/model_registry.json).",
    )
    args = ap.parse_args()
    generate_cards(registry_path=args.registry, out_dir=args.out)


if __name__ == "__main__":
    main()
