"""a short air quality fact for each day.

written and reviewed here rather than generated, for the same reason the health
guidance is: this goes out as a push notification in more than fifty languages,
and nobody on the team can read most of them to check what was sent.

each fact has to be true, useful to someone in an African city, and
understandable without any background. no statistics we cannot source, and
nothing about how our own estimates are produced.
"""

from datetime import date as dt_date
from typing import List, Optional

# repeats after len(FACTS) days, indexed by date.toordinal() % len(FACTS) so
# everyone sees the same fact on the same day and nobody sees one twice.
FACTS: List[str] = [
    "Cooking indoors over wood or charcoal is one of the biggest sources of harmful smoke in the home. Opening a window while you cook helps more than you would think.",
    "Air pollution is usually worst in the early morning and again in the evening, when traffic is heavy and the air near the ground is still.",
    "Wind clears polluted air. A still, hot day often means worse air than a breezy one, even when nothing else has changed.",
    "Rain washes dust and smoke out of the air. The hours after a heavy downpour are often the cleanest of the week.",
    "Fine dust is the part of air pollution that matters most for health, because it is small enough to travel deep into the lungs.",
    "Burning rubbish releases far more harmful smoke than burning wood. Even a small fire close to the house affects the air indoors.",
    "Walking one street away from a busy road can noticeably reduce what you breathe in on the way to work or school.",
    "Children breathe faster than adults and are closer to the ground, so they take in more of what is in the air.",
    "During the harmattan, dust from the Sahara can travel thousands of kilometres and settle over cities far from any desert.",
    "Keeping windows closed on a dusty day, then airing the house once the dust settles, keeps indoor air noticeably cleaner.",
    "Older people and anyone with asthma or heart trouble feel bad air first, often before anyone else notices anything.",
    "A cloth mask does little against fine dust. If you need protection on a bad day, a close fitting mask does much more.",
    "Idling engines in traffic put out pollution without moving anyone. Switching off while waiting genuinely helps the street.",
    "Trees and hedges along a road trap some of the dust from traffic before it reaches nearby homes.",
    "Air pollution does not stop at a city boundary. Smoke from farm burning outside town can settle over the whole city.",
    "Generators produce concentrated fumes. Placing one away from windows and doors keeps those fumes out of the house.",
    "Sweeping raises dust back into the air. Damp cloth or a damp mop keeps it down instead.",
    "Air quality can differ noticeably between two ends of the same city, depending on traffic, industry and wind.",
    "Charcoal stoves keep giving off fumes after the flame dies down. Take them outside once the cooking is finished.",
    "Exercising hard means breathing more deeply, so a run on a bad air day takes in far more than a walk would.",
    "Smoke from burning fields can travel for days and affect towns hundreds of kilometres away.",
    "Dust indoors settles on surfaces and gets stirred up again. Regular damp cleaning reduces what everyone breathes.",
    "The air is often cleanest in the middle of the day, once the morning traffic has cleared and the air has begun to move.",
    "Living close to an unpaved road usually means more dust indoors, especially in the dry season.",
    "Pregnant women are advised to avoid heavy smoke, because what she breathes reaches the baby too.",
    "A haze that blurs buildings in the distance usually means a lot of fine dust in the air.",
    "Kerosene lamps give off fumes in the room where they burn. Better lighting improves indoor air as well as sight.",
    "Air pollution is linked to more coughs, chest infections and asthma attacks, especially in children.",
    "The dry season usually brings worse air than the rainy season, because there is nothing to wash the dust away.",
    "Standing behind a vehicle while it starts means breathing the most concentrated part of its exhaust.",
    "Good ventilation matters most in the room where cooking happens, not in the rest of the house.",
    "Roadside food stalls sit in traffic fumes all day. A stall set back from the road is better for the cook as well as the customer.",
    "Cleaner cookstoves cut both smoke and the amount of fuel needed, so they save money as well as lungs.",
    "Smoke from one household affects the neighbours too. Air is shared in a way water and electricity are not.",
    "On a bad air day, indoors with the windows shut is usually cleaner than outdoors.",
    "Fine dust can stay suspended for hours after the wind that lifted it has dropped.",
    "Asthma inhalers work best when used before symptoms get bad. On a poor air day, keep one within reach.",
    "Burning plastic gives off fumes that are harmful even in small amounts. It is never a safe way to get rid of it.",
    "Air quality tends to improve on days when public transport replaces many separate car journeys.",
    "A closed car in traffic can hold more pollution inside it than the street outside.",
    "Damp indoor air encourages mould, which affects breathing in its own way alongside smoke and dust.",
    "Older engines put out far more than newer ones. A well maintained vehicle pollutes noticeably less.",
    "Children's outdoor play is worth timing away from the morning and evening traffic peaks.",
    "Dust masks help outdoors but do nothing about smoke inside the house. Ventilation is what helps there.",
    "Air pollution affects the heart as well as the lungs, which is why doctors take it seriously for older patients.",
    "A single day of very bad air can trigger symptoms in someone whose asthma is normally well controlled.",
    "Cities near the coast often have cleaner air, because sea breezes keep the air moving.",
    "Cooking with a lid on uses less fuel and produces less smoke for the same meal.",
    "Air pollution is one of the leading environmental health risks worldwide, and much of it is preventable.",
    "Smoke settles into clothes and bedding. Airing them out reduces what people breathe overnight.",
    "The safest time to open the house up is usually when there is a light breeze and no nearby burning.",
    "Long exposure to moderate pollution can matter more for health than one very bad day.",
    "Roadside dust is heavier than smoke and settles faster, which is why the far side of a hedge is noticeably cleaner.",
    "Anyone who feels tightness in the chest on a hazy day should treat that as a signal to go indoors.",
    "Improving air quality shows up in fewer hospital visits for breathing problems within weeks, not years.",
    "Burning waste at night does not make the smoke safer. It just makes it harder to see.",
    "Two cities with the same weather can have very different air, depending on traffic and what is burned nearby.",
    "Keeping the cooking area separate from where children sleep reduces what they breathe over a whole night.",
    "Air quality is worst close to the ground, which is exactly where small children spend their time.",
    "Small changes repeated daily, such as cooking with better ventilation, add up to more than any single big effort.",
    "If outdoor air looks brownish or grey, cut outdoor exercise short and prefer shaded side streets over open highways.",
    "Closing doors and windows during a nearby fire or rubbish burn, then airing later, keeps most of the smoke out.",
    "Wetting dusty yards before sweeping or playing reduces how much fine dust rises into the air children breathe.",
    "Sitting upstairs or higher in a building can mean cleaner air than street level when traffic fumes hug the ground.",
    "If your eyes sting and your throat feels scratchy outdoors, treat that as a cue to move indoors sooner.",
    "Parking far from the school gate and walking the last stretch cuts the time children stand in idling exhaust.",
    "Covering food and water during dusty weather keeps settled dust from ending up in meals and drinking cups.",
    "A short walk after rain often means cleaner air than the same route on a dry, still afternoon.",
    "Fans move air around but do not clean it. Opening to a breeze when outdoor air is decent matters more.",
    "If a neighbour burns plastic or painted wood, close windows on that side of the house until the smoke clears.",
    "Babies in prams ride closer to exhaust pipes than adults walking beside them, so choose quieter side roads when you can.",
    "Washing hands and face after a dusty commute reduces how much settled dust you later rub into eyes and mouth.",
    "Diesel fumes smell stronger than petrol, and that smell is a useful warning to step away from the roadside.",
    "Hanging laundry indoors on a very dusty day keeps grit out of bedding that you will breathe all night.",
    "School sports on a hazy morning are harder on young lungs than the same drill after the air has cleared.",
    "A simple chimney or hood over a cookstove sends smoke up and out instead of into the room.",
    "If you must travel on a dusty road, crack a window slightly rather than recirculating stale cabin air for hours.",
    "Markets near junctions collect more traffic smoke. Shopping earlier, before peak traffic, can feel easier to breathe.",
    "People recovering from chest infections should treat hazy days like sick days and rest indoors when possible.",
    "Clearing ash and charcoal remnants outdoors, not in the kitchen, stops leftover fumes from filling the house.",
    "Bus stops under trees or set back from the curb often feel less choked than those right beside accelerating traffic.",
    "During crop-burning season, a sudden drop in visibility is a signal to keep children indoors more of the day.",
    "Sealing gaps around poorly fitting windows with cloth strips can cut how much street dust blows into bedrooms.",
    "If you cough more on weekdays than weekends, traffic along your usual route may be part of the reason.",
    "Carrying water on dusty paths kicks up less dust if you walk slowly and avoid dragging sandals through dry soil.",
    "Open sewers and rotting waste add unpleasant gases to street air. Crossing upwind of them is a small daily help.",
    "Night markets with many generators create pockets of fumes. Standing a few metres upwind makes a real difference.",
    "When harmattan haze arrives, rinse noses with clean water or saline if your clinic recommends it for irritation.",
    "Choosing solid fuel that is dry and fully seasoned produces less smoke than damp wood that smoulders.",
    "Teachers can help by keeping classroom windows shut during the dustiest hour, then airing at break time.",
    "Motorcycle taxis put riders in a dense stream of exhaust. A helmet with a face shield also blocks some grit.",
    "If indoor smoke makes you watery-eyed while cooking, improve airflow before you add more fuel to the fire.",
    "Construction sites throw up dust all day. Walking on the opposite side of the road reduces what you inhale.",
    "People with heart disease should avoid hurrying through thick traffic smoke, because strain and fumes stack together.",
    "A damp scarf over the nose helps with large grit but is not enough alone on a day of very fine dust.",
    "Turning off the stove the moment cooking ends stops unnecessary smoke from lingering in a closed kitchen.",
    "Shared courtyards stay cleaner when rubbish is collected rather than burned in the corner each evening.",
    "Early morning jogs along major roads often mean breathing yesterday's settled dust plus today's first rush hour.",
    "If your child wheezes more in the dry season, plan outdoor play for clearer hours and keep medicine ready.",
    "Street vendors who cook with charcoal can place the stove at the back of the stall, away from customers' faces.",
    "After a dust storm, wipe floors before you dry-sweep, or you will loft the same dust back into the air.",
    "Rooms with many people and little airflow can feel stuffy even when outdoor air is fine. Brief airing helps.",
    "Avoid lighting incense or mosquito coils in small sealed rooms where infants sleep through the night.",
    "Commuters waiting in long queues of idling cars breathe more fumes than those who walk a parallel footpath.",
    "If factory smoke blows toward your home at certain hours, plan outdoor chores for times when the wind shifts.",
    "Cleaning cooking pots outside after a smoky meal keeps leftover soot from clinging to indoor walls and fabrics.",
    "Children sleeping on floor mats near open doorways take in more street dust than those on raised beds farther in.",
    "A sudden smell of burning rubber or plastic outdoors is a reason to close up and wait before exercising.",
    "Public parks away from highways usually offer cleaner air for walking than pavements along busy dual carriageways.",
    "Using less oil for deep frying cuts kitchen smoke as well as grease on walls and ceilings.",
    "If you work outdoors all day, take short indoor breaks when the haze thickens rather than pushing through it.",
    "Covering sand and gravel piles on building sites with tarpaulin stops wind from spreading dust into nearby homes.",
    "People who iron clothes with charcoal irons should do so near a doorway or window, not in a sealed bedroom.",
    "When buses belch black smoke, stepping back until they pull away is a simple habit that reduces a sharp exposure.",
    "Boiling water for tea with a lid on shortens the time the fire needs to burn and the smoke it releases.",
    "Clinic waiting areas near busy roads benefit from closed street-facing windows during peak traffic hours.",
    "If your street floods then dries to powder, that dried mud becomes dust. Dampening it again keeps it down.",
    "Sharing rides cuts the number of engines on the road, which is one of the few ways a neighbourhood can clear air together.",
    "Avoid burning treated timber or old furniture; the coatings release fumes far worse than plain wood smoke.",
    "Gardeners sweeping leaves into piles should mist them lightly first so the dust does not rise into faces.",
    "On still evenings, smoke from many kitchens can pool in low-lying streets. Higher ground often feels clearer.",
    "Packing school bags and shoes by the door overnight saves a rushed morning wait beside idling school traffic.",
    "If you smell generator fumes indoors, find the intake path and block it, then move the machine farther away.",
    "Wearing glasses on dusty days keeps grit out of eyes that you would otherwise rub with dusty hands.",
    "Restaurants that fry outdoors send less smoke into dining rooms, which helps both staff and guests.",
    "A week of moderate haze can leave you more tired than usual. Extra rest is a reasonable response, not laziness.",
    "Choosing walking routes behind buildings rather than along the curb reduces how much exhaust reaches you.",
    "Keep spare inhalers at school and at home so a sudden bad-air day does not catch a child without medicine.",
    "Drying fish or meat over smoky fires outdoors is better for household air than doing the same work inside.",
    "If neighbours sweep the road dry every morning, ask about wetting first; the whole street breathes the result.",
    "Taxi drivers who crack windows at traffic lights exchange cabin air instead of trapping exhaust from the car ahead.",
    "Thick curtains that stay closed all dry season can hold dust. Shake them outdoors on a clearer day.",
    "People fasting or skipping meals may feel pollution more; staying hydrated still helps mucous membranes cope.",
    "When trucks dump sand for building, wait a few minutes downwind before walking past the fresh pile.",
    "Kitchen doors that open onto a corridor spread cooking smoke through the house. A window to the outside is better.",
    "If your chest feels tight only in one room, check for a smouldering coal pot, lamp, or blocked vent there.",
    "Community clean-ups that haul waste away beat community burn piles for the air everyone shares afterward.",
    "Cyclists should favour service lanes and quieter streets when the main road is a continuous line of exhaust.",
    "Warm, stagnant nights after hot days often hold more pollution near the ground until morning breezes return.",
    "Teaching children not to play next to generators or running engines is a habit that protects them for years.",
    "A bowl of water near a dusty doorway will not clean the air, but wiping surfaces with that water will help.",
    "If you must burn garden waste, do it in small amounts on a breezy day, far from houses and water sources.",
    "Office workers near open windows above a bus park may need to close up during the evening rush.",
    "Shoes left outside on dusty days bring less grit onto floors where babies crawl and play.",
    "People with chronic cough should note which days feel worse; patterns often line up with traffic or burning.",
    "Covered drains and sealed waste bins cut smells and some of the gases that make street air harder to bear.",
    "Grilling meat over open flame outdoors keeps the thickest smoke out of living rooms and sleeping areas.",
    "When visibility drops so you can barely see the next block, postpone non-essential outdoor errands.",
    "Classrooms crowded after dusty break times benefit from a few minutes of quiet with windows adjusted for airflow.",
    "Buying charcoal that is fully carbonised and not half-burned wood means less smoke when you light the stove.",
    "Residents near unpaved alleys can agree on occasional watering of the worst stretches before peak foot traffic.",
    "If smoke from a dump fire lasts for days, limit outdoor drying of clothes until the plume moves on.",
    "Standing upwind at a fuel station while the tank fills keeps you out of the strongest vapour cloud.",
    "Parents can check the sky before sending children to outdoor games; a sharp haze is reason to choose indoor play.",
    "Repairing exhaust leaks on old vehicles helps the driver's cabin as well as everyone walking nearby.",
    "Sleeping with a smoky mosquito coil beside the bed is hard on lungs; place coils farther away near ventilation.",
    "Food wrapped at the stall, then eaten indoors away from traffic, cuts how much roadside air you take in with the meal.",
    "When the wind comes from industrial areas, hang laundry later rather than collecting a film of grit on wet cloth.",
    "Brief, gentle walks are kinder on bad-air days than long, hard workouts that force deep breathing.",
    "Households that switch from open fires to improved stoves often notice fewer morning coughs within months.",
    "Crossing the street to walk on the side with fewer buses can lower the fumes you breathe on the same commute.",
    "Dust on ceiling fans spreads when the blades spin. Wipe blades on a clearer day before you turn them on.",
    "If a child has more night coughs in the dry months, ask a clinician whether air and dust are aggravating it.",
    "Queueing inside a shop instead of on the pavement beside traffic is a small choice that adds up over a year.",
    "Open windows on the side of the house opposite a busy road often bring cleaner air than street-facing ones.",
    "People who haul goods by cart along dusty tracks can wet scarves and rest in shade when the air feels thick.",
    "Turning compost rather than burning garden scraps keeps nutrients in the soil and smoke out of the street.",
    "A clear blue sky after rain is a good window for airing mattresses, curtains, and stored clothes.",
    "Mechanics working in pits under vehicles should take breaks in fresher air, not only in the fume-filled bay.",
    "If your street holds festivals with many generators, plan quieter indoor time for elders and small children.",
    "Using matches or a clean lighter instead of plastic scraps to start a fire avoids a burst of toxic starter smoke.",
    "Drivers who warm up cars for long periods outside bedrooms push fumes toward sleepers; shorter warm-ups help.",
    "When harmattan dust coats every surface, vacuuming or damp wiping daily beats one big dry clean-up later.",
    "Street food cooks can raise pots on stands so smoke rises above customers sitting close to the flame.",
    "If you feel short of breath climbing stairs only on hazy days, take it slower and rest indoors afterward.",
    "Community leaders who ban open burning near schools protect children during the hours they must be outside.",
    "Carrying an umbrella on dusty windy days shields the face a little and signals others that conditions are rough.",
    "Rooms used for both cooking and sleeping need the strongest push for chimneys, fans to the outside, or both.",
    "After fireworks or celebratory burning, the next morning's air can still be poor; delay outdoor exercise then.",
    "Choosing ripe, dry crop residues for fuel burns cleaner than green cuttings that smoke for a long time.",
    "People waiting for lifts at the roadside can stand a few metres back from the curb until the vehicle stops.",
    "Wiping window sills weekly in the dry season removes dust that would otherwise recirculate every time you open up.",
    "If a workplace fills with welding or paint fumes, step outside for breaks rather than eating lunch in that air.",
    "Families can agree on a no-burn rule for household plastic, even when rubbish collection is delayed.",
    "A humid rainy afternoon often feels easier to breathe than a hot dry one with the same amount of traffic.",
    "Keeping chickens or animals from scratching dusty yards near doorways reduces how much grit enters the house.",
    "When trucks idle outside your shop all afternoon, asking them to switch off while loading is fair to everyone nearby.",
    "Children walking home in a pack can take a slightly longer quiet lane instead of the smoky main road together.",
    "If your only fan blows air from a smoky courtyard indoors, turn it off until outdoor smoke thins.",
    "Regular engine servicing that stops black smoke protects the driver's health and the street's air at once.",
    "On days when the horizon disappears into haze, treat outdoor chores as optional and indoor rest as wise.",
]


def fact_for(day: Optional[str] = None) -> str:
    """the fact for a given day. everyone sees the same one on the same date."""
    d = dt_date.fromisoformat(day) if day else dt_date.today()
    return FACTS[d.toordinal() % len(FACTS)]
