// writes a build stamp the running app can show and a /version.json that is
// never cached. without this there is no way to tell whether a deploy actually
// reached the browser: "it still looks the same" and "it did not deploy" are
// indistinguishable from the outside.
import { writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

function sh(cmd, fallback) {
  try {
    return execSync(cmd, { cwd: root, stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return fallback;
  }
}

const commit = sh("git rev-parse --short HEAD", "unknown");
const branch = sh("git rev-parse --abbrev-ref HEAD", "unknown");
const builtAt = new Date().toISOString();
let version = "1.0.0";
try {
  version = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8")).version || version;
} catch {
  /* keep default */
}

const stamp = { version, commit, branch, builtAt };

const outDir = resolve(root, "public");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  resolve(outDir, "version.json"),
  JSON.stringify(stamp, null, 2) + "\n"
);
writeFileSync(
  resolve(root, "src/buildInfo.js"),
  `// generated by scripts/gen-version.mjs, do not edit\n` +
    `export const BUILD_INFO = ${JSON.stringify(stamp)};\n`
);
console.log(`generated version stamp ${version} ${commit} (${branch}) at ${builtAt}`);
