/**
 * Major African cities only — capitals and well-known metros.
 * Not neighbourhoods / suburbs (e.g. Ashaley Botwe, Ikoyi).
 */
export const AFRICAN_CITIES = [
  'Abidjan',
  'Abuja',
  'Accra',
  'Addis Ababa',
  'Alexandria',
  'Algiers',
  'Antananarivo',
  'Asmara',
  'Bamako',
  'Bangui',
  'Banjul',
  'Bissau',
  'Blantyre',
  'Brazzaville',
  'Bulawayo',
  'Cairo',
  'Cape Town',
  'Casablanca',
  'Conakry',
  'Cotonou',
  'Dakar',
  'Dar es Salaam',
  'Djibouti',
  'Douala',
  'Durban',
  'Freetown',
  'Gaborone',
  'Harare',
  'Ibadan',
  'Johannesburg',
  'Kampala',
  'Kano',
  'Khartoum',
  'Kigali',
  'Kinshasa',
  'Kumasi',
  'Lagos',
  'Libreville',
  'Lilongwe',
  'Lomé',
  'Luanda',
  'Lusaka',
  'Maputo',
  'Marrakech',
  'Maseru',
  'Mbabane',
  'Mogadishu',
  'Monrovia',
  'Nairobi',
  "N'Djamena",
  'Niamey',
  'Nouakchott',
  'Ouagadougou',
  'Port Harcourt',
  'Port Louis',
  'Porto-Novo',
  'Praia',
  'Pretoria',
  'Rabat',
  'Tripoli',
  'Tunis',
  'Windhoek',
  'Yaoundé',
] as const
