[server]
headless = false
address = "localhost"
port = 8501
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "poll"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
